# Generated by Django 3.0.14 on 2023-09-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='horario_autorização',
            new_name='horario_autorizacao',
        ),
    ]
