# Generated by Django 3.0.14 on 2023-09-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20230928_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='porteiro',
            new_name='registrado_por',
        ),
    ]
